apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: avro-consumer-pipeline
spec:
  vertices:
    - name: in
      volumes:
        - name: kafka-config-volume
          configMap:
            name: avro-consumer-config
            items:
              - key: user.configuration
                path: user.configuration.yaml
              - key: consumer.properties
                path: consumer.properties
      scale:
        min: 1
        max: 1
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-java/kafka-java:v0.5.2
            args: [ "--spring.config.location=file:/conf/user.configuration.yaml", "--consumer.properties.path=/conf/consumer.properties" ]
            imagePullPolicy: Always
            volumeMounts:
              - name: kafka-config-volume
                mountPath: /conf
    - name: sink
      scale:
        min: 1
        max: 1
      sink:
        log:
          { }
  edges:
    - from: in
      to: sink